// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVV_fGfbQFe7OhWRt1Q5gwfOX-pSCXUag',
    appId: '1:916189893174:web:c419433560aee903593e97',
    messagingSenderId: '916189893174',
    projectId: 'technai',
    authDomain: 'technai.firebaseapp.com',
    storageBucket: 'technai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_EiXURpirTzAcR50jmtZqPfzG1NTzm9A',
    appId: '1:916189893174:android:f90cbb7a3d969db1593e97',
    messagingSenderId: '916189893174',
    projectId: 'technai',
    storageBucket: 'technai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3C454XO9ezeQVVSqJY2qGK3ZXhAUfqcw',
    appId: '1:916189893174:ios:f161ae07f2d7da3d593e97',
    messagingSenderId: '916189893174',
    projectId: 'technai',
    storageBucket: 'technai.firebasestorage.app',
    iosBundleId: 'com.example.technai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3C454XO9ezeQVVSqJY2qGK3ZXhAUfqcw',
    appId: '1:916189893174:ios:f161ae07f2d7da3d593e97',
    messagingSenderId: '916189893174',
    projectId: 'technai',
    storageBucket: 'technai.firebasestorage.app',
    iosBundleId: 'com.example.technai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVV_fGfbQFe7OhWRt1Q5gwfOX-pSCXUag',
    appId: '1:916189893174:web:d99a00ab6d27ab0b593e97',
    messagingSenderId: '916189893174',
    projectId: 'technai',
    authDomain: 'technai.firebaseapp.com',
    storageBucket: 'technai.firebasestorage.app',
  );
}
